services:
  postgres:
    image: quay.io/debezium/postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=native
      - POSTGRES_PASSWORD=native
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql